{% set name = "pybroom" %}
{% set version = "0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybroom-{{ version }}.tar.gz
  sha256: c500af430a0c39d5fdf576e60f0a0a1f61028f144a3ba43dba26a15bdac4c395

build:
  number: 1003
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lmfit
    - pandas

test:
  imports:
    - pybroom
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pybroom.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Broom for python: convert fit results to tidy pandas.DataFrame.'
  description: |
    Pybroom is a small python 3+ library for converting collections
    of fit results (curve fitting or other optimizations) to Pandas DataFrame
    in tidy format (or long-form). Once fit results are in tidy DataFrames,
    it is possible to leverage common patterns for tidy data analysis.
    and visual explorations
  doc_url: http://pybroom.readthedocs.io/
  dev_url: https://github.com/tritemio/pybroom

extra:
  recipe-maintainers:
    - tritemio
