appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Dq7pR4kjWcvfmV12azpLEZf+LyX5IF0uu63U5w4Wm6nnGKyjiYzx6ccMgPJ4Rt27YKm0q8z1qUaeAtl6EJvWjJY8kZp5VSvsmtjs//+NrmwtLFAMZDHFWX7NCLFgUNSCVDMUVhNzO7pgSUsDaMZfuZR+nWZL651or826hHr7eiWFtgMnyFxQHybIHLQSCF2AZBCCLkXiByQpY050QNj/M07liad5+NU4RkMSd9e8M28HCig85zlmRZ3JXF63NfJbsPAqUYfMLb3l38CqHeKHcU4dBm8GWJbPw0pLveVCI5Evgyf1GH/4y48jZ6u+LQWnupRXfysibVIfJNkbt5pRnlSc4WytMB5Yk/+AXeXR4+7MHK4tijzOe1EvxXKeGITKHdGFuzzgO+1054vhRZdgtAaNPHKpOsHROrtaxJZUC8AcQerk+rTF1eyrAReZb2wwML7UjyW5jynIu1JLQ3kPjPLKi0xhs+0vPVVUqyRRg7RDsertWWR99uXAWkUxwwpqYo3Jf8EoldwMw/GI+w+PONOIT1OEE4XSuShlWZtvvbaIPryL2+qDRzoH4pLw5FargpzaGRZsm1tNeuQDCRZCaSikckVOa/JVArwv1HM0jlgcbbYOr91BouJTWuQYydig6QV0IxCYXgYnpd838VXO+3pI5SnzTe8GLN6n4EUinFc=}
