travis:
  secure:
    BINSTAR_TOKEN: 08FW7F4sfBQycny06CPwFcss4r1CLQZ9mqow9Uq/+uIayPrBWfyAiG3Q0vFIxxYKwGITyuz83/c/byW5TECiygEmGBNCV7nOhZKxtryYIcoW0Xj1+A9sTOfUU9cz0Z/c8gjGvkLTKgnsNEwHmO0E1FQXOu61V2/sVkR7MAH10MMJbgOh5YFc29sN/+u6CJ/0sI+rMw3I9IB9uh8GWhGYIbx5/2YDQlj68hVjuzIqyvWPr0JcG/ScPp78NLh55uskSTUL4GWCIeOH7hegIJA1/WVdXm91yDcWjDJnq++8PrQdCB6QN2E7jPnkIEJgIQ175lm2AJH5temwioxySAu6FrMYBQIKbH/pCE9eQkHeMGI1KVD6C0ep1qlRSOMAbNGHIhw4XHgWyV8EqE/LdgBQzqxPbzxorepAt5acXZHlkkEFRJ6oN/LiZmD2buFth0TJhr5S0+93fPpEVJXrkooEq4sHwJuj+uVAzJCgMRG0F48s8LO0B2yKkw/vYWyG9Scmf4yxqYv8OvwoCvsNaYObk5KMR9tJo9o+59x6jcr8nqrzolWlgEUilbzuMZlH5JWex2hUd4YUe4uXkn+qy11m5HF4l9K0/4IrrJ2VQKSfSAtOeFIH5iKHOOvCGb0SMnKRjx6YnaR2W4J/nxV/GzVk8e/0xquSSxNpWoeEmay9+oc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
